### PR TITLE
Fixed Nanoloop mode in Teensy

### PR DESCRIPTION
**Pull request by lpla**
Fixed Nanoloop sync mode when used with a Teensy.

### CODE REVIEW

**Comment by lpla** [comment]
Also, looking at the issues, this should fix #9

**Comment by trash80** [comment]
The "extended midi mode for mGB" makes no sense as that can was/is handled by the arduino. Technically it allows any channel to any gameboy synth. passing the buck to mGB to process the data is bad by design since any processing that can be handled externally should be.

**Comment by trash80** [comment]
image

**Comment by lpla** [comment]
This was implemented to allow using three independent Game Boys simultaneously with one Arduinoboy, for example.

**Comment by trash80** [comment]
True. Though it shouldn't be modified by mGB, but rather a feature in Arduinoboy. I don't understand why one would create a custom mGB for this as it's much easier to manage in Arduino.

**Comment by lpla** [comment]
Well, if you connect three Game Boys with something like Synccross (https://github.com/lpla/synccross) and the Arduinoboy (with both master branch and my modifications), using stock mGB all Game Boys respond to the same 5 MIDI channels (which is 1 to 5 as hardcoded in mGB).

But with the modified mGB versions I linked, with master branch code you can only manage 5 channels, as you shown in the screenshot of the editor. Like, the PU1 of GB1, the PU1 of GB2, Poly of GB3, Noise of GB1 and Noise of GB2, for example, by mapping the editor channel values with the ones that the modified mGB's respond. But all the other Game Boy channels cannot be controlled.

With my changes you can use all channels and poly modes of all Game Boys at the same time independently, and still one MIDI channel is left unused.

Sorry if this wasn't clear.

**Comment by trash80** [comment]
Hmm.. Needs more poking. Would need to see the affects of these changes. Each feature should be separate PRs unless they are codependent. I was going to test the initial PR when I made it out to the studio to test the changes.

**Comment by trash80** [comment]
I also imagine a passive splitter with having all the data being sent to all gameboys would make each gameboy unreliable. (At least on DMG) since all data is processed. I am hesitant to have that feature in master.

**Comment by lpla** [comment]
I am splitting this PR in several, as it contains many changes. I left it as it was initially.

**Pull request merged**
